# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
pages_dir: ./_pages
# collections: null
# 
# Handling Reading
# safe:         true
sitemap:      true

include:      [".htaccess", "_pages"]

exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""

# Outputting
permalink:     /:title.html
paginate: 10
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

markdown: kramdown
permalink: pretty

# Credits content
credits: 'test'
